# Agent Mode Runbook
# ==================
#
# This YAML file defines a set of standard jobs for the Maven agent
# to execute.  Each job is made up of one or more steps.  Steps
# reference tooling provided within the repository (e.g. scripts under
# tools/) or built-in operations (e.g. health_sweep).  Outputs
# specify the location of any generated reports.

jobs:
  phase1_read_only:
    description: |
      Perform a read‑only validation of the Maven system.  This job
      executes the health sweep across all cognitive brains and domain
      banks, recalculates the template integrity and compares it to
      the recorded manifest.  No writes occur.
    steps:
      - health_sweep: true
      - integrity_verify: true
    outputs:
      - reports/agent/phase1_health.json
      - reports/agent/phase1_integrity.json

  phase2_repair:
    description: |
      Perform repair and maintenance tasks.  Requires an auth token
      from the Policy Engine.  The agent will scan for banned files,
      create a backup, perform cold compaction and apply any
      authorised repairs.  Steps that modify the repository MUST be
      guarded by a valid token scoped to the requested operation.
    steps:
      - banned_file_scan: true
      - backup: true
      - compact_cold: true
      - repair: true
    outputs:
      - reports/agent/phase2_repair.json

  phase3_proof:
    description: |
      Re‑run the read‑only validation after a repair operation to
      produce a before/after comparison.  This demonstrates that
      repairs did not introduce new issues.
    steps:
      - health_sweep: true
      - integrity_verify: true
    outputs:
      - reports/agent/phase3_comparison.json

  alignment_audit:
    description: |
      Perform a read‑only alignment audit.  This job discovers all cognitive
      and governance brains and domain banks, maps directives from the
      specification and companion addendum to code modules, executes a simple
      smoke pipeline, and writes an alignment matrix, findings and proof to
      the reports directory.  No modifications occur.
    steps:
      - alignment_audit: true
    outputs:
      - reports/agent/alignment_matrix.json
      - reports/agent/alignment_findings.json
      - reports/agent/alignment_proof.json

  alignment_propose:
    description: |
      Generate a patch list based on the latest alignment audit.  This job
      reads any existing alignment findings and produces a JSON patch list
      identifying files and modules that need to be updated or removed to
      satisfy the specification.  No modifications occur.
    steps:
      - alignment_propose: true
    outputs:
      - reports/agent/patchlist.json

  alignment_apply:
    description: |
      Apply an alignment patch list generated by a prior alignment_propose.
      This job requires a valid governance token to authorise any
      modifications.  For the stub implementation, it simply records
      that the apply was attempted and succeeds when a token beginning with
      'GOV-' is provided.
    steps:
      - alignment_apply: true
    outputs:
      - reports/agent/alignment_apply_result.json